name: Node.js Package

on:
  push:
    branches:
      - "RD-637_gh-action-cdn-release"
  release:
    types: [created]

env:
  CDN_MODULE_NAME: "maptiler-ar-control"
  CDN_VERSION: "v.test"
  CDN_REPO: "maptiler/cdn.maptiler.com"
  CDN_REPO_BRANCH: "maptiler-ar-control-test"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - run: npm ci

      - run: npm run make
      
      # - name: Publish NPM package (regular)
      #   if: "!github.event.release.prerelease"
      #   run: |
      #     npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      # - name: Publish NPM package (pre-release)
      #   if: "github.event.release.prerelease"
      #   run: |
      #     npm publish --tag next
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Check if target directory exists and abort if it does
        run: |
          if [ -d "cdn/${CDN_MODULE_NAME}/${CDN_VERSION}" ]; then
            echo "Directory cdn/${CDN_MODULE_NAME}/${CDN_VERSION} already exists. Aborting."
            exit 1
          fi

      - name: Checkout CDN repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CDN_REPO }}
          path: cdn

      - name: List files in target-repo
        run: |
          node -p "require('./package.json').version"
          # mkdir -p cdn/${CDN_MODULE_NAME}/${CDN_VERSION}
          # cp -r build/* cdn/${CDN_MODULE_NAME}/${CDN_VERSION}
          # cd cdn
          # git config user.name "github-actions"
          # git config user.email "github-actions@github.com"
          # git checkout -b "${CDN_REPO_BRANCH}" || git checkout "${CDN_REPO_BRANCH}"
          # git add .
          # git commit -m "Add ${CDN_MODULE_NAME} ${CDN_VERSION}"
          # git push origin "${CDN_REPO_BRANCH}"